GET {{host-url}}/product

###

GET {{host-url}}/cart

###

POST {{host-url}}/cart
Content-Type: application/json

{
  "productId": "B0001",
  "quantity": 4
}

###

POST {{host-url}}/login
Content-Type: application/json

{
  "username": "customer1@email.com",
  "password": "123",
  "rem": true
}

###

GET {{host-url}}/cart
Content-Type: application/json
Authorization: Bearer {{token}}


###

POST {{host-url}}/cart
Content-Type: application/json
Authorization: Bearer {{token}}

[
]

###

PUT {{host-url}}/cart/B0002
Content-Type: application/json
Authorization: Bearer {{token}}

1

###
POST {{host-url}}/cart/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "quantity": 4,
  "productId": "B0002"
}

###

DELETE {{host-url}}/cart/B0002
Content-Type: application/json
Authorization: Bearer {{token}}

###

POST {{host-url}}/cart/checkout
Content-Type: application/json
Authorization: Bearer {{token}}


###

GET {{host-url}}/order
Authorization: Bearer {{token}}

###

